### ISSUE TITLE
Cloudflare R2 support upgrade

### ISSUE THREAD

**Issue by chancefcc** [tiktagus/tiktag-s3#7]
## Adding CF R2 Support

Current `tiktag` cli for hosting an asset is like,
```
tiktag image.png
```
By default, current version uses the credentials under the `minio` section of `~/.tiktag/config.yaml` to media files onto the bucket of the specified object storage services, MinIO, as defined on this section.

After this upgrade, a user can run either
```
tiktag minio image.png
```
 or
```
tiktag  r2 image.png
```
to host media files on the pre-defined object storage service.

## Improve `~/.tiktag/config.yaml`

Rename these params to match the idioms used in their corresponding services/apps,

Old
```
minio:
  endpoint: "s3.myminio.com"
  id: "my_bucket_api_id"
  secret: "my_bucket_secret"
  useSSL: true
  bucketName: "my_bucket"
```

New
```
minio:
  endpoint: "s3.myminio.com"
  accessKey: "my_bucket_api_id"
  secretKey: "my_bucket_secret"
  useSSL: true
  bucketName: "my_bucket"
```

## Naming conventions

All params naming shall follow the corresponding object storage's conventions, EXACTLY as they are used.
